import Head from 'next/head'
import Banner from '../components/Banner';
import { Container } from "../styles/pages/home";
import { FiNavigation, FiTruck } from "react-icons/fi";
import { BsCoin, BsGeoAlt } from "react-icons/bs";
export default function Home() {
  return (
    <div className="content">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
    <Container>
      <div className="MenuForms">
          <div className="BtnForm">
            <FiNavigation   size={50}/>
            <h2>Emissão de e-WB</h2>
          </div>
          
          <div className="BtnForm">
            <FiTruck   size={50} />
            <h2>Coletas</h2>
          </div>
          
          <div className="BtnForm">
            <BsGeoAlt   size={50} />
            <h2>Rastreamento</h2>
          </div>
          
          <div className="BtnForm">
            <BsCoin   size={50} />
            <h2>Cotações</h2>
          </div>
      </div>
    </Container>
        </div>
   
  )
}
